### ISSUE TITLE
employees can see emails 

### ISSUE THREAD

**Issue by YutingMao1993** [IITIDIDX597/sp_2019_team1#13]
#user stories
as an employee, who wants to make great events and engage people 
I want to be able to see members email.

**Comment by YutingMao1993** [comment]
so that I can contact people

**Comment by evanwchan** [comment]
As an employee who has limited discretionary time,
I want Hatch to connect me with other egg leaders,
so that I can quickly and conveniently start the planning process.

**Comment by akallish** [comment]
> As an employee who has limited discretionary time,
> I want Hatch to connect me with other egg leaders,
> so that I can quickly and conveniently start the planning process.

Hey @evanwchan, good start. Here is another iteration:

**As an** employee 
**I want** Hatch to connect me with other egg leaders,
**so that** I can quickly and conveniently start the planning process due to my limited discretionary free time

**Comment by YutingMao1993** [comment]
as an employee, who values good communications, 
I want to get employees email,
so that I can contact people

**Comment by akallish** [comment]
> as an employee, who values good communications,
> I want to get employees email,
> so that I can contact people

Hey @YutingMao1993 How about this:
**as an** employee
**I want** to have access to specific employees email addresses that I value
**so that** I can contact them

**Comment by akallish** [comment]
@YutingMao1993 and @evanwchan For each story there should be one issue. Do not put all stories in one Issue.

**Comment by evanwchan** [comment]
**As an** employee
**I want** Hatch to connect me with other egg leaders,
**so that** I can quickly and conveniently start the planning process due to my limited discretionary free time

**Sub-hill:** Employees who sign up to lead planning are 
connected via email by Hatch to kick off their 
working together or include new leaders.

**Part of hill:** "can lead the planning and delivery of events" in What and "boost ownership" in Wow


**Comment:** This issue and sub-hill does seem a bit off the mark since it more indirectly connects with the hill. It isn't directly addressing employees signing up to lead, but rather how the leaders can form a team, which isn't something that's included in the hill. @akallish, would you say this is an accurate assessment?

**Comment by akallish** [comment]
@evanwchan @YutingMao1993 Sorry for the lapse in time. Agreed. Also where is your epic tag?

**Comment by YutingMao1993** [comment]
do I need to put each subhills for each user story?

**Comment by YutingMao1993** [comment]
i do not know what is epic tag

**Comment by evanwchan** [comment]
@akallish, because this story doesn't quite ladder up to the hill directly, should we throw away this story?

> @evanwchan @YutingMao1993 Sorry for the lapse in time. Agreed. Also where is your epic tag?

**Comment by YutingMao1993** [comment]
> **as an** employee, who values good communications,
>**I want** to get employees email,
>**so that** I can contact people

> **Sub-hill:** Employees who sign up to lead planning are
> connected via email by Hatch to kick off their
> working together or include new leaders.
> 
> **Part of hill:** "can lead the planning and delivery of events" in What and "boost ownership" in Wow
>

**Comment by YutingMao1993** [comment]
>> I upload  the new vision 
>
> > **as an** employee,
> > **I want** to have access to specific employees email addresses that I value 
> > **so that** I can contact them
> 
> > **Sub-hill:** Employees who sign up to lead planning are
> > connected via email by Hatch to kick off their
> > working together or include new leaders.
> > **Part of hill:** "can lead the planning and delivery of events" in What and "boost ownership" in Wow
